[project]
name = "dqn-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[box2d,classic-control]>=1.2.1",
    "numpy>=2.3.4",
    "pillow>=12.0.0",
    "ray>=2.51.0",
    "swig>=4.4.0",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
    "wandb>=0.22.2",
]
